### Label and Ordinal Encoding

Label Encoding

In [1]:
## Creating DataFrame
import pandas as pd

df = pd.DataFrame({'color': ['red', 'blue', 'green', 'green', 'red', 'blue']})
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [2]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

lbl_encoder.fit_transform(df[['color']])

c:\Users\ermoh\OneDrive\Desktop\Data-Analyst\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [3]:
## Adding new data
lbl_encoder.transform([['red']])

c:\Users\ermoh\OneDrive\Desktop\Data-Analyst\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [4]:
lbl_encoder.transform([['green']])

c:\Users\ermoh\OneDrive\Desktop\Data-Analyst\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [5]:
lbl_encoder.transform([['blue']])

c:\Users\ermoh\OneDrive\Desktop\Data-Analyst\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

Ordinal Encoding

In [6]:
from sklearn.preprocessing import OrdinalEncoder

## creating a DataFrame
df = pd.DataFrame({'size': ['small', 'medium', 'large', 'medium', 'small', 'large']})
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [7]:
## creating OrdinalEncoder instance
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [8]:
## adding new data
encoder.transform([['medium']])

c:\Users\ermoh\OneDrive\Desktop\Data-Analyst\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])